{
    "name": "Instance Creator",
    "summary": """
    Instance creator for brandtrendy. This is the app.
    """,
    "author": "Vauxoo",
    "website": "https://www.vauxoo.com",
    "license": "OPL-1",
    "category": "Installer",
    "version": "19.0.1.0.0",
    "depends": [
        "approvals",
        "contacts",
        "documents",
        "fleet",
        "hr_attendance",
        "hr_expense",
        "hr_skills",
        "iot",
        "knowledge",
        "l10n_mx_edi_stock",
        "maintenance",
        "mrp",
        "project",
        "quality_control",
        "repair",
        "sale_margin",
        "sign",
        "spreadsheet_dashboard",
        "stock_barcode",
        "stock_landed_costs",
        "survey",
        "website_helpdesk",
        "website_slides",
        "website_sale",
    ],
    "data": [
        "data/res_company_data.xml",
        "data/res_partner_data.xml",
        "views/account_bank_statement_line_views.xml",
        "views/helpdesk_ticket_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
